package cuit.xsgw.base.db.dao;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

import cuit.xsgw.base.db.table.Status;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig statusDaoConfig;

    private final StatusDao statusDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        statusDaoConfig = daoConfigMap.get(StatusDao.class).clone();
        statusDaoConfig.initIdentityScope(type);

        statusDao = new StatusDao(statusDaoConfig, this);

        registerDao(Status.class, statusDao);
    }

    public void clear() {
        statusDaoConfig.clearIdentityScope();
    }

    public StatusDao getStatusDao() {
        return statusDao;
    }

}
